-n -1

diff --git a/netlify-simple/action.yml b/netlify-simple/action.yml
--- a/netlify-simple/action.yml
+++ b/netlify-simple/action.yml
@@ -77,11 +77,11 @@ runs:
         echo $PR_API
         curl --no-progress-meter -L -H "Accept: $ACCEPT" -H "X-GitHub-Api-Version: $VERSION" $PR_API?per_page=$COMMENT_NUMBER > comments.json
         cat comments.json
-        echo '    "id":0000' >> comments.json
+        echo '    "id":so grep does not pipefail' >> comments.json
         cat comments.json
         grep '^    "id"' comments.json | sed s/[^0-9]//g > comment_ids_0.txt
         cat comment_ids_0.txt
-        head -$COMMENT_NUMBER comment_ids_0.txt > comment_ids.txt
+        head -n -1 comment_ids_0.txt > comment_ids.txt
         cat comment_ids.txt
         N_COMMENTS=$(cat comment_ids.txt | wc -l)
         echo $N_COMMENTS
